<Project>
    <PropertyGroup>        
        <Version>2.0.1</Version>        
        <AssemblyVersion>2.0.1</AssemblyVersion>
        <PackageTags>Music, Bogus</PackageTags>
        <ResolveAssemblyReferencesSilent>true</ResolveAssemblyReferencesSilent>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    </PropertyGroup>
</Project>