<Project>
    <PropertyGroup>        
        <Version>1.0.1</Version>        
        <AssemblyVersion>1.0.2</AssemblyVersion>
        <PackageTags>Music, Bogus</PackageTags>
        <ResolveAssemblyReferencesSilent>true</ResolveAssemblyReferencesSilent>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    </PropertyGroup>
</Project>